/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnRouteImport } from './routes/en'
import { Route as ZhRouteImport } from './routes/zh'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnTeamRouteImport } from './routes/en.team'
import { Route as ZhIndexRouteImport } from './routes/zh.index'
import { Route as ZhTeamRouteImport } from './routes/zh.team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhRoute = ZhRouteImport.update({
  id: '/zh',
  path: '/zh',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const EnTeamRoute = EnTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => EnRoute,
} as any)
const ZhIndexRoute = ZhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZhRoute,
} as any)
const ZhTeamRoute = ZhTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ZhRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRouteWithChildren
  '/zh': typeof ZhRouteWithChildren
  '/en/team': typeof EnTeamRoute
  '/zh/team': typeof ZhTeamRoute
  '/en/': typeof EnIndexRoute
  '/zh/': typeof ZhIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en/team': typeof EnTeamRoute
  '/zh/team': typeof ZhTeamRoute
  '/en': typeof EnIndexRoute
  '/zh': typeof ZhIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRouteWithChildren
  '/zh': typeof ZhRouteWithChildren
  '/en/team': typeof EnTeamRoute
  '/zh/team': typeof ZhTeamRoute
  '/en/': typeof EnIndexRoute
  '/zh/': typeof ZhIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/en' | '/zh' | '/en/team' | '/zh/team' | '/en/' | '/zh/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/en/team' | '/zh/team' | '/en' | '/zh'
  id:
    '__root__' | '/' | '/en' | '/zh' | '/en/team' | '/zh/team' | '/en/' | '/zh/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRoute: typeof EnRouteWithChildren
  ZhRoute: typeof ZhRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh': {
      id: '/zh'
      path: '/zh'
      fullPath: '/zh'
      preLoaderRoute: typeof ZhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/team': {
      id: '/en/team'
      path: '/team'
      fullPath: '/en/team'
      preLoaderRoute: typeof EnTeamRouteImport
      parentRoute: typeof EnRoute
    }
    '/zh/': {
      id: '/zh/'
      path: '/'
      fullPath: '/zh/'
      preLoaderRoute: typeof ZhIndexRouteImport
      parentRoute: typeof ZhRoute
    }
    '/zh/team': {
      id: '/zh/team'
      path: '/team'
      fullPath: '/zh/team'
      preLoaderRoute: typeof ZhTeamRouteImport
      parentRoute: typeof ZhRoute
    }
  }
}

interface EnRouteChildren {
  EnTeamRoute: typeof EnTeamRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnTeamRoute: EnTeamRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface ZhRouteChildren {
  ZhTeamRoute: typeof ZhTeamRoute
  ZhIndexRoute: typeof ZhIndexRoute
}

const ZhRouteChildren: ZhRouteChildren = {
  ZhTeamRoute: ZhTeamRoute,
  ZhIndexRoute: ZhIndexRoute,
}

const ZhRouteWithChildren = ZhRoute._addFileChildren(ZhRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRoute: EnRouteWithChildren,
  ZhRoute: ZhRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
